modulename = 'ui'
usertokenexpire = 86400

[database]
db = 'ruomu'
driver = 'mysql'
host = '127.0.0.1'
password = 'root'
port = 3306
prefix = 't_'
showsql = true
user = 'root'

[logger]
backups = 7
compress = false
dir = 'logs'
level = 'debug'
maxage = 30
maxsize = 100

[project]
id = 28010609669849088

[redis]
app = 'ruomu'
host = '127.0.0.1'
password = '123456'
port = 6379

[server]
port = 8888
