userTokenExpire=86400

[server]
port=8888
#viewsDir=""
#viewExtension=".html"

[logger]
level="debug"
dir="logs"
backups=7
maxSize=100
maxAge=30
compress=false

[redis]
app="ruomu"
host="127.0.0.1"
port=6379
password="123456"
#maxIdle=50
#maxActive=100

[database]
driver="mysql" # sqlite mysql pg postgres
host="127.0.0.1"
port=3306
user="root"
password="root"
db="ruomu"
prefix="t_"
showSql=true